### ISSUE TITLE
 an entirely undeclared routine in the switch, doesn't report the missing right-hand-side

### ISSUE THREAD

**Issue by duffy-ocraven** [zeek/spicy#193] opened 2020-04-15 00:19 UTC
```
module Issue_193_undeclared_routine_in_switch;

public type AmongNmbrs = unit {
  oneMember: uint8;
  switch (self.oneMember) {
   0x32 -> : getGrandChild;
    * -> : null;
  };
};
```
with a routine in the switch that is entirely undeclared, spicy doesn't report the missing right-hand-side of the -> :, Not even when that is the case triggered (as printf "2" would). 
```
2417 /usr/local/etc/tmp/spicy$printf "1\n" | build/bin/spicy-driver ../Issue_193_undeclared_routine_in_switch.spicy
2418 /usr/local/etc/tmp/spicy$printf "2\n" | build/bin/spicy-driver ../Issue_193_undeclared_routine_in_switch.spicy
```

**Comment by bbannier** [comment] 2021-03-03 15:28
I am closing this since I cannot reproduce this issue with 04db810f0bd4daae969c338f598c4b42516e0d0e which for your example now produces the following:

```
printf "1\n" | spicy-driver foo.spicy
[error] foo.spicy:6:11: unknown ID 'getGrandChild'
[error] foo.spicy:7:9: unknown ID 'null'
[error] spicy-driver: aborting after errors
```

**Closed by bbannier** 2021-03-03 15:28 UTC
Labels: Diagnostics, On-deck
