### ISSUE TITLE
fails in cxx syntax: safeint_internal::numeric_type< T >::isInt, "Integer type required"

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#212] opened 2020-04-21 01:42 UTC
```
module TryingVector;
 tsPrep();

function tsPrep() {
  local tsSinceEpoch: uint64 = 0;
  local debugOctet: uint8 = 0x21;
  YearAndMonthByte(tsSinceEpoch, 2000, debugOctet);
}

function YearAndMonthByte(inout tsSinceEpoch: uint64, Year: uint64, rawTwoNybbleOfMonth: uint8) : string {
    local PriorMonthsesDays: vector<uint64> = [0,31,59,90, 120,151,181,212, 243,273,304,334];
    if (1970 <= Year) {
      tsSinceEpoch = Year * 365 * 86400;
      tsSinceEpoch -= (1970 * 365 * 86400);
      local Months: uint64;
      local leapYears: uint64 = ((Year - 1969) / 4);
      tsSinceEpoch += (leapYears * 86400);
      if ( 9 < rawTwoNybbleOfMonth >> 4) {
        Months = 0;
      }
      else {
        Months = (rawTwoNybbleOfMonth >> 4);
      }	    
      if (rawTwoNybbleOfMonth & 0x0F <= 9) {
        Months += 10 * (rawTwoNybbleOfMonth & 0x0F);
      }
      if (0 == (Year % 4) && (2 < Months)) {
        tsSinceEpoch += 86400;
      }
      tsSinceEpoch += (PriorMonthsesDays[Months - 1] * 86400);
    }
}
```
gets through spicy syntax checks, but fails in cxx syntax:
```
3148 /usr/local/etc/tmp/spicy$ build/bin/spicyc -j ../Issue_212_MonthVector.spicy 
In file included from TryingVector.cc:6:
In file included from /usr/local/etc/tmp/spicy/hilti/include/hilti/rt/libhilti.h:14:
In file included from /usr/local/etc/tmp/spicy/hilti/include/hilti/rt/safe-int.h:5:
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:825:9: error: static_assert failed due to requirement 'safeint_internal::numeric_type<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >::isInt' "Integer type required"
        static_assert(safeint_internal::numeric_type< T >::isInt, "Integer type required");
        ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:858:96: note: in instantiation of template class 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >' requested here
            isBothLT32Bit = (safeint_internal::int_traits< T >::isLT32Bit && safeint_internal::int_traits< U >::isLT32Bit),
                                                                                               ^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:876:55: note: in instantiation of template class 'safeint_internal::type_compare<unsigned long long, hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >' requested here
        IntZone_UintLT32_UintLT32 = safeint_internal::type_compare< T,U >::isBothUnsigned && safeint_internal::type_compare< T,U >::isBothLT32Bit,
                                                      ^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:1753:19: note: in instantiation of template class 'IntRegion<unsigned long long, hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >' requested here
        method = (IntRegion< T,U >::IntZone_UintLT32_UintLT32  ? MultiplicationState_CastUint :
                  ^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:6687:33: note: in instantiation of template class 'MultiplicationMethod<unsigned long long, hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >' requested here
    MultiplicationHelper< T, U, MultiplicationMethod< T, U >::method >::template MultiplyThrow< E >( (T)rhs, lhs, ret );
                                ^
TryingVector.cc:41:97: note: in instantiation of function template specialization 'operator*<unsigned long long, hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > >, hilti::rt::integer::detail::SafeIntException>' requested here
        tsSinceEpoch += PriorMonthsesDays[Months - hilti::rt::integer::safe<std::uint64_t>{1u}] * hilti::rt::integer::safe<std::uint64_t>{86400u};
                                                                                                ^
In file included from TryingVector.cc:6:
In file included from /usr/local/etc/tmp/spicy/hilti/include/hilti/rt/libhilti.h:14:
In file included from /usr/local/etc/tmp/spicy/hilti/include/hilti/rt/safe-int.h:5:
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:859:113: error: no member named 'isLT64Bit' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
            isBothLT64Bit = (safeint_internal::int_traits< T >::isLT64Bit && safeint_internal::int_traits< U >::isLT64Bit)
                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:876:55: note: in instantiation of template class 'safeint_internal::type_compare<unsigned long long, hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >' requested here
        IntZone_UintLT32_UintLT32 = safeint_internal::type_compare< T,U >::isBothUnsigned && safeint_internal::type_compare< T,U >::isBothLT32Bit,
                                                      ^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:1753:19: note: in instantiation of template class 'IntRegion<unsigned long long, hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >' requested here
        method = (IntRegion< T,U >::IntZone_UintLT32_UintLT32  ? MultiplicationState_CastUint :
                  ^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:6687:33: note: in instantiation of template class 'MultiplicationMethod<unsigned long long, hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >' requested here
    MultiplicationHelper< T, U, MultiplicationMethod< T, U >::method >::template MultiplyThrow< E >( (T)rhs, lhs, ret );
                                ^
TryingVector.cc:41:97: note: in instantiation of function template specialization 'operator*<unsigned long long, hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > >, hilti::rt::integer::detail::SafeIntException>' requested here
        tsSinceEpoch += PriorMonthsesDays[Months - hilti::rt::integer::safe<std::uint64_t>{1u}] * hilti::rt::integer::safe<std::uint64_t>{86400u};
                                                                                                ^
In file included from TryingVector.cc:6:
In file included from /usr/local/etc/tmp/spicy/hilti/include/hilti/rt/libhilti.h:14:
In file included from /usr/local/etc/tmp/spicy/hilti/include/hilti/rt/safe-int.h:5:
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:877:175: error: no member named 'isLT64Bit' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
        IntZone_Uint32_UintLT64   = safeint_internal::type_compare< T,U >::isBothUnsigned && safeint_internal::int_traits< T >::is32Bit && safeint_internal::int_traits< U >::isLT64Bit,
                                                                                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:1753:19: note: in instantiation of template class 'IntRegion<unsigned long long, hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >' requested here
        method = (IntRegion< T,U >::IntZone_UintLT32_UintLT32  ? MultiplicationState_CastUint :
                  ^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:6687:33: note: in instantiation of template class 'MultiplicationMethod<unsigned long long, hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >' requested here
    MultiplicationHelper< T, U, MultiplicationMethod< T, U >::method >::template MultiplyThrow< E >( (T)rhs, lhs, ret );
                                ^
TryingVector.cc:41:97: note: in instantiation of function template specialization 'operator*<unsigned long long, hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > >, hilti::rt::integer::detail::SafeIntException>' requested here
        tsSinceEpoch += PriorMonthsesDays[Months - hilti::rt::integer::safe<std::uint64_t>{1u}] * hilti::rt::integer::safe<std::uint64_t>{86400u};
                                                                                                ^
In file included from TryingVector.cc:6:
In file included from /usr/local/etc/tmp/spicy/hilti/include/hilti/rt/libhilti.h:14:
In file included from /usr/local/etc/tmp/spicy/hilti/include/hilti/rt/safe-int.h:5:
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:878:177: error: no member named 'is32Bit' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
        IntZone_UintLT32_Uint32   = safeint_internal::type_compare< T,U >::isBothUnsigned && safeint_internal::int_traits< T >::isLT32Bit && safeint_internal::int_traits< U >::is32Bit,
                                                                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:880:178: error: no member named 'is64Bit' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
        IntZone_UintLT64_Uint64    = safeint_internal::type_compare< T,U >::isBothUnsigned && safeint_internal::int_traits< T >::isLT64Bit && safeint_internal::int_traits< U >::is64Bit,
                                                                                                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:883:158: error: no member named 'isLT64Bit' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
        IntZone_Uint32_IntLT64    = safeint_internal::int_traits< T >::isUint32 && std::numeric_limits< U >::is_signed && safeint_internal::int_traits< U >::isLT64Bit,
                                                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:884:160: error: no member named 'isInt32' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
        IntZone_UintLT32_Int32    = !std::numeric_limits< T >::is_signed && safeint_internal::int_traits< T >::isLT32Bit && safeint_internal::int_traits< U >::isInt32,
                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:885:158: error: no member named 'isLT64Bit' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
        IntZone_Uint64_Int        = safeint_internal::int_traits< T >::isUint64 && std::numeric_limits< U >::is_signed && safeint_internal::int_traits< U >::isLT64Bit,
                                                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:886:160: error: no member named 'isInt64' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
        IntZone_UintLT64_Int64    = !std::numeric_limits< T >::is_signed && safeint_internal::int_traits< T >::isLT64Bit && safeint_internal::int_traits< U >::isInt64,
                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:887:119: error: no member named 'isInt64' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
        IntZone_Uint64_Int64      = safeint_internal::int_traits< T >::isUint64 && safeint_internal::int_traits< U >::isInt64,
                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:890:173: error: no member named 'isLT64Bit' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
        IntZone_Int32_IntLT64     = safeint_internal::type_compare< T,U >::isBothSigned && safeint_internal::int_traits< T >::is32Bit && safeint_internal::int_traits< U >::isLT64Bit,
                                                                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:891:175: error: no member named 'is32Bit' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
        IntZone_IntLT32_Int32     = safeint_internal::type_compare< T,U >::isBothSigned && safeint_internal::int_traits< T >::isLT32Bit && safeint_internal::int_traits< U >::is32Bit,
                                                                                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:892:173: error: no member named 'isInt64' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
        IntZone_Int64_Int64       = safeint_internal::type_compare< T,U >::isBothSigned && safeint_internal::int_traits< T >::isInt64 && safeint_internal::int_traits< U >::isInt64,
                                                                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:893:173: error: no member named 'isLT64Bit' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
        IntZone_Int64_Int         = safeint_internal::type_compare< T,U >::isBothSigned && safeint_internal::int_traits< T >::is64Bit && safeint_internal::int_traits< U >::isLT64Bit,
                                                                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:894:175: error: no member named 'is64Bit' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
        IntZone_IntLT64_Int64     = safeint_internal::type_compare< T,U >::isBothSigned && safeint_internal::int_traits< T >::isLT64Bit && safeint_internal::int_traits< U >::is64Bit,
                                                                                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:897:158: error: no member named 'isLT32Bit' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
        IntZone_Int32_UintLT32    = safeint_internal::int_traits< T >::isInt32 && !std::numeric_limits< U >::is_signed && safeint_internal::int_traits< U >::isLT32Bit,
                                                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:898:159: error: no member named 'isUint32' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
        IntZone_IntLT64_Uint32    = std::numeric_limits< T >::is_signed && safeint_internal::int_traits< T >::isLT64Bit && safeint_internal::int_traits< U >::isUint32,
                                                                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:899:158: error: no member named 'isLT64Bit' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
        IntZone_Int64_UintLT64    = safeint_internal::int_traits< T >::isInt64 && !std::numeric_limits< U >::is_signed && safeint_internal::int_traits< U >::isLT64Bit,
                                                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:900:111: error: no member named 'isUint64' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
        IntZone_Int_Uint64        = std::numeric_limits< T >::is_signed && safeint_internal::int_traits< U >::isUint64 && safeint_internal::int_traits< T >::isLT64Bit,
                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/etc/tmp/spicy/hilti/include/hilti/3rdparty/SafeInt/SafeInt.hpp:901:118: error: no member named 'isUint64' in 'safeint_internal::int_traits<hilti::rt::vector::detail::AssignProxy<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException>, std::__1::allocator<SafeInt<unsigned long long, hilti::rt::integer::detail::SafeIntException> > > >'
        IntZone_Int64_Uint64      = safeint_internal::int_traits< T >::isInt64 && safeint_internal::int_traits< U >::isUint64
                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
20 errors generated.
[error] jit: failed to execute compilation action.
[error] jit: failed to compile C++ code unit TryingVector to bitcode
[error] spicyc: JIT compilation failed
3149 /usr/local/etc/tmp/spicy$
```

**Comment by rsmmr** [comment] 2020-04-21 10:25
Depending on whether the code is correct or not (which I haven't tracked through yet), this might actually be a bug instead of diagnostics.

**Comment by rsmmr** [comment] 2020-04-30 10:16
Minimal reproducer:

```
module Test;

function x() {
    local a: uint64 = 1;
    local b: vector<uint64> = [2];
    a += b[0];
    assert a == 3;
}
```

**Comment by rsmmr** [comment] 2020-04-30 10:17
@bbannier this fails because of the `b[0]` yielding an AssignProxy, not the integer it expects. Wondering if your vector changes help already, or what else we can do there.

**Comment by bbannier** [comment] 2020-04-30 10:33
> @bbannier this fails because of the `b[0]` yielding an AssignProxy, not the integer it expects. Wondering if your vector changes help already, or what else we can do there.

I don't think just #273 would fix this. We could depending on `T` conditionally add a couple more operators to `AssignProxy<T>`; for primitive types this would be e.g., `operator+=` (required here) and similar, for other types we'd also need `operator->` etc.

**Comment by rsmmr** [comment] 2020-05-04 06:59
Can we identify the cases where we'd need to insert the cast? Would it need to be any operation that may yield an assign proxy, except those where we'll actually do an assignment? I believe the code generator could tell that, but I'd need to see.

Alternatively, adding those operators doesn't seem like a bad solution either. For ADL, we could add templates that just forwards to `T`.

**Comment by bbannier** [comment] 2020-05-04 11:08
@rsmmr, we'd need to explicitly coerce in codegen in all places where we'd have a subscript on the LHS of an assignment. We'd want to emit the equivalent of this:
```
auto xs = Vector<integer::safe<int>>({0});

int y = 0;
y += (const decltype(xs)::value_type&)(xs[0]);
```

This is due to us using `AssignProxy` to perform lazy bounds checks; would we perform eager bounds checks this issue wouldn't arise, e.g., the following would work today:
```
auto xs = Vector<integer::safe<int>>({0});

int y = 0;
y += xs.at(0);  // Eagerly throws `std::out_of_range`.
```

Re:manually adding all needed operators, while this might work in this case, we'd not only would have to add operators for built-in types for this case, but also for wrappers like `integer::safe`. If we cannot avoid conversion of `AssignProxy` to `integer::safe` we'll also have to fully make `AssignProxy<T>` behave like a `T` even under any type traits used anywhere (e.g., currently we don't have `std::is_integer_v<AssignProxy<int>>`); to do that we'd probably inherit `AssignProxy` from `T` if `T` is not a built-in, and else manually add operators. I'd hope coercing in codegen would be simpler.

**Comment by bbannier** [comment] 2020-05-04 12:56
FYI, removing the lazy validation feature from `Vector` by removing all of `AssignProxy` leads to two failed tests which both seem to rely on the autoresizing of the container when assigning to an out of range index,
```
$ btest -r -d
[  0%] hilti.types.vector.default-values ... failed
  % '${HILTIC} -j /Users/bbannier/src/spicy/tests/.tmp/hilti.types.vector.default-values/default-values.hlt >output' failed unexpectedly (exit code 1)
  % cat .stderr
  uncaught exception hilti::rt::IndexError: vector index 1 out of range (/Users/bbannier/src/spicy/tests/.tmp/hilti.types.vector.default-values/default-values.hlt:18:1)

[ 50%] hilti.types.vector.ops ... failed
  % '${HILTIC} -j /Users/bbannier/src/spicy/tests/.tmp/hilti.types.vector.ops/ops.hlt >output' failed unexpectedly (exit code 1)
  % cat .stderr
  uncaught exception hilti::rt::IndexError: vector index 5 out of range (/Users/bbannier/src/spicy/tests/.tmp/hilti.types.vector.ops/ops.hlt:16:1)

```

**Comment by rsmmr** [comment] 2020-05-04 13:24
Hmm, yeah, that makes sense. It would be good to keep that behavior, otherwise vectors get awkward to use. Can you think of another way of implementing this?

Btw, I just checked and unit & map likewise have AssignProxies.

**Comment by bbannier** [comment] 2020-05-04 14:07
> Hmm, yeah, that makes sense. It would be good to keep that behavior, otherwise vectors get awkward to use. Can you think of another way of implementing this?

For non-`const` `Vector`s we could eagerly resize the `Vector` and return a ref to the (now present valid) element; this is now somewhat like e.g., `std::map`'s `operator[]` for which for non-`const` `map`s creates new entries. The behavior for `const` `Vector`s is already like we would want it (eager & validating). I believe this would work fine `Vector`s of default-constructible `T`.

**Comment by bbannier** [comment] 2020-05-04 14:28
Eagerly resizing preserves almost all of the existing behavior, but makes the following test reduced from `/hilti.types.vector.ops/ops.hlt:19:1` fail,
```
local auto v = vector("a", "b", "c");
assert-exception hilti::print(v[100]); // Does not throw anymore; element 100 is default-initialized.
```

This looks like acceptable behavior to me.

**Comment by rsmmr** [comment] 2020-05-04 14:45
> assert-exception hilti::print(v[100]); // Does not throw anymore; element 100 is default-initialized.

That's a non-modifying RHS-side access, is there a way we could steer
that to the non-resizing index operator?

If not, yes, I think we could live with the auto-resizing even on such
reads.

Robin

-- 
Robin Sommer * Corelight, Inc. * robin@corelight.com * www.corelight.com

**Closed** 2020-05-05 12:26 UTC
Labels: Runtime Library
