### ISSUE TITLE
Resynchronizing on unit error when failure happens after the first field.

### ISSUE THREAD

**Issue by Mohan-Dhawan** [zeek/spicy#1847] opened 2024-08-28 21:04 UTC
When chunked data is read into a sink, the analyzer throws a violation if a TCP ACKed unseen segment is present. The violation is of the form `view starts before available range`. A reproducer has been shared privately with @bbannier.

**Comment by rsmmr** [comment] 2024-08-29 07:15
Sorry, but this isn't really useful as a ticket because the scope is completely unclear. Spicy doesn't even have a notion of TCP ACKing; if anything, that's Zeek-side. I'm closing this, but feel free to reopen once it has been scoped down to something actionable.

**Comment by sethhall** [comment] 2024-08-31 13:36
Sort of unrelated, but Mohan and I poked around synchronization yesterday and accidentally discovered where this bug actually lies.  It looks like if the field failure happens in the first field of the structure, then synchronization happens correctly, but if it happens in a field after that there is an error and recovery doesn't occur.  It turns out that all of the gap tests only test the failure occurring in the first field of the unit. The best part is that we have a short and easy to understand reproducer script!

This works fine...

```spicy
module Test;

type Blah = unit {
    ab: /AB/;
    cd: /CD/;
};

public type X = unit {
    x: (Blah &synchronize)[];

    on %synced { print "Confirming with state: %s" % self; confirm; }
    on %done { print self; }
};
```

with this spicy-driver batch file...
```
!spicy-batch v2
@begin-flow id1 stream Test::X
@data id1 1
A
@gap id1 1
@data id1 6
CDABCD
@end-flow id1
```

```sh
❯ spicy-driver -F test7.dat test7.spicy
Confirming with state: [$x=[]]
[$x=[[$ab=b"AB", $cd=b"CD"]]]
```

but if we force the error to occur in the second field by letting the first field be fully populated (the first 'C' is missing) with this batch file we get the error...
```
!spicy-batch v2
@begin-flow id1 stream Test::X
@data id1 2
AB
@gap id1 1
@data id1 5
DABCD
@end-flow id1
```

```sh
❯ spicy-driver -F test7.dat test7.spicy
error for ID id1: view starts before available range (test7.spicy:9:5-9:29)
```

Hopefully this is boiled down enough to pinpoint where the problem is.   I tested this in several different ways and as far as I can tell the failures seem to be centered around where in the unit the errors are happening.  It leads me to believe that some state in the stream is being mutated and not reset once fields have been successfully parsed and an error happens later in the unit structure (I'm also crossing my fingers that this means this bug might be easily fixed!)

**Comment by rsmmr** [comment] 2024-09-04 16:36
I've started to look into this, but no leads yet.

**Comment by rsmmr** [comment] 2024-09-05 07:07
Right, see Benjamin's note above.

**Comment by sethhall** [comment] 2024-09-05 12:18
Ugh, I totally missed that he pointed out the commit. Anyway, first time I've used git bisect and that was definitely worthwhile learning.

**Closed** 2024-09-11 06:20 UTC
Labels: Bug, Regression

**Comment by sethhall** [comment] 2024-09-11 12:25
I think this bug was in 1.11, would it justify a 1.11.2?   This bug does break most practical uses of synchronize.

**Comment by Mohan-Dhawan** [comment] 2024-09-13 10:26
Will it be backported to Zeek v7.0.1?

**Comment by rsmmr** [comment] 2024-09-13 11:32
Yes, it will be in 1.11.2 and 7.0.2.
