### ISSUE TITLE
Surprising "auto cannot be used for variable declaration"

### ISSUE THREAD

**Issue by awelzel** [zeek/spicy#1792] opened 2024-07-11 18:48 UTC
Slight duplicate of #1790, but I was surprised by the "type 'auto' cannot be used for variable declaration" - is that needed/useful?
```
$ cat strange.spicy 
module Test;

type T = unit() {
  x: uint8;
};

public type U = unit() {
  len: uint32;

  ts: T[] &size=self.len {
    for ( e in self.tss )  # typoed and should just be $$
      print e.x;
  }
};
$ spicyc -j strange.spicy -o /tmp/x.hlto
[error] strange.spicy:11:5-12:16: type 'auto' cannot be used for variable declaration
[error] strange.spicy:11:16-11:23: unsupported operator: <Test::U>.tss
[error] strange.spicy:12:13-12:15: unsupported operator: <auto>.x
[error] spicyc: aborting after errors
```

**Comment by rsmmr** [comment] 2024-07-12 07:38
It's a prioritization issue in the output: the right error is the 2nd (modulo #1790), the 1st and 3rd are follow-ups that would better be suppressed (which is possible, just needs a bit of additional logic in the validator).

**Comment by bbannier** [comment] 2024-07-16 09:37
Similar to #1790, marking this as a regression since before #1462 we would have reported

```
[error] foo.spicy:11:19-11:26: type does not have field 'tss'
[error] foo.spicy:12:19-12:19: unknown ID 'e'
[error] spicyc: aborting after errors
```

**Closed** 2024-10-17 08:35 UTC
Labels: Diagnostics, Priority Low, Regression
